### ISSUE TITLE
Query returns error

### ISSUE THREAD

**Issue by Xhiro-Yui** [jikan-me/jikan#111]
When sending a GET request to Jikan 

`https://api.jikan.me/search/anime/gbf/`

The strings `gbn`, `gbk` and some others have the same behaviour.

The response obtained is 

`{
  "error": "File does not exist"
}`

Tested from the website [Jikan - Apiary](https://jikan.docs.apiary.io/#reference/0/character/search-request-examples?console=1). It works for any other length 3 string just not this specific string.

**Comment by irfan-dahir** [comment]
This is indeed odd. The search query basically parses from this page `https://myanimelist.net/anime.php?q=`.

I went ahead and and put this in the URL `https://myanimelist.net/anime.php?q=gbn` and apparently instead of showing the search results page which the Jikan parses off of, it shows this page:
https://myanimelist.net/anime/3372/RGB_Adventure

The only reason I can think up of is that, that is the only search result so MAL automatically redirects to it.

I think I can have a workaround by showing the redirection page as a single result. Thanks for opening an issue regarding this, unfortunately a fix for this will have to wait until [REST 2.2](https://github.com/jikan-me/jikan/projects/1).

**Comment by irfan-dahir** [comment]
Note: This fix will be available from REST v2.2 when it's out.
