### ISSUE TITLE
[Season] Currently airing status / Popularity / Ranked

### ISSUE THREAD

**Issue by IgorMCesar** [jikan-me/jikan#151]
Hello again hahaha

So, i was making a filter for seasons and noticed this info is missing. Is it possible to add it?

Thanks in advance =)
(Please tell if i am making too many issues, not my intention to disturb)

**Comment by irfan-dahir** [comment]
Hey, no worries. I appreciate the request but unfortunately that is not possible since the filter on the season page is the work of some JS/Ajax.

However enough data is returned, e.g; `score`, `genre`, `score`, `r18_plus`, `kids`, etc. So you can make the request and filter it out locally on your client.

**Comment by IgorMCesar** [comment]
Let me ask you something, based on your answer. Is it ok to get all seaon (200+ animes) and make a request for each anime everytime i need seasonal info? Just curious if that`s an aceptble solution to my problem. If yes, whats the best way to do it? Request individually?

**Comment by irfan-dahir** [comment]
How are you exactly implementing this? Through an app/website?

If so, I'd simply request the seasonal data (and filter if needed) and display it with the given information. And once a user clicks on an anime from the list, it'll load up and display the anime's details by making a request for the anime's data.
