### ISSUE TITLE
Inconvenient episodes fetching

### ISSUE THREAD

**Issue by KyuBlade** [jikan-me/jikan#188]
Hi,

I need to get the all the episodes of an anime to display them, but with the current paging system, for One Piece it makes 9 requests to do, wait a wait of 3 secs required for bulk requests, between each request it takes a lot of time.
It would be good to have a way to get the whole list without additional data around.
I find it very strange to get the anime resource concatenated with the meta ressource queried when fetching a meta route.

Thanks.

**Comment by irfan-dahir** [comment]
Hi! The concatenated part is depreciated in V3; you should switch over to V3 since it's much faster with additional anime resources and for more goodies too.

As for the episodes, it would be impossible to show all the pages. Episode pages are paginated and each page only lists 100 episodes on MyAnimeList.

Parsing all the pages all together would hit MAL's rate limit and the response from Jikan would be **huge**.

For any sort of app, the current way of fetching episodes is optimal. And you won't have to add a 3 second delay because the user doesnt behave like a bot. However if this is for data dumping — what I refer to as "bulk requests", a delay would be required.

Hope that helps!

**Comment by KyuBlade** [comment]
I see, so I can request two times per second without delay.
Gonna see to switch to v3 then.

Thanks.

**Comment by irfan-dahir** [comment]
If you've been using V2 for a while, you might want to read the migration notes as well.

https://github.com/jikan-me/jikan-rest/blob/master/MIGRATION.MD
