### ISSUE TITLE
not show getGenres() 

### ISSUE THREAD

**Issue by KarimQaderi** [jikan-me/jikan#193]
v2
use
```
$Anime = $jikan->getAnime((new \Jikan\Request\Anime\AnimeRequest(21)));
 return $anime->getGenres();
```

![image](https://user-images.githubusercontent.com/32425175/45284416-c29f3100-b4f5-11e8-9ce2-fd4464301aa5.png)

Please fix

**Comment by irfan-dahir** [comment]
```
$anime = $jikan->getAnime(
    new \Jikan\Request\Anime\AnimeRequest(21)
);

var_dump($anime->getGenres());
```
![screenshot from 2018-09-10 17-30-20](https://user-images.githubusercontent.com/9166451/45297743-c9429e00-b51f-11e8-892f-700c08f8819f.png)


Works for me. To debug this further can you answer a few questions for me?

1. Are you using a Proxy/VPN?
2. Are you making this request from your PC or a server?
3. Can you tell me the response for `var_dump($anime->getGenres());`?

**Comment by KarimQaderi** [comment]
tnx
1. vpn
2. PC
3. work var_dump
4. no

![image](https://user-images.githubusercontent.com/32425175/45305523-c18af580-b52f-11e8-805c-3c78ff3334c8.png)

**Comment by irfan-dahir** [comment]
I mentioned you in the discord channel. Can you tell us what happens when you `return $anime->getGenres();`? As shown in your image, it seems to be encoded to JSON.

The parser seems to be working fine on your end, it seems that you're using `json_encode` on the `$anime` response - or whatever Router framework you're using is doing that. Basically converting the `$anime` object directly to JSON will **not** work.

If that is indeed the case, you will need a serializer to convert the `$anime` to JSON.
https://jmsyst.com/libs/serializer

**Comment by KarimQaderi** [comment]
Thank you, my work started

use return 
![image](https://user-images.githubusercontent.com/32425175/45284416-c29f3100-b4f5-11e8-9ce2-fd4464301aa5.png)

use var_dump
![image](https://user-images.githubusercontent.com/32425175/45305523-c18af580-b52f-11e8-805c-3c78ff3334c8.png)
