### ISSUE TITLE
Can't fetch a user's anime list anymore.

### ISSUE THREAD

**Issue by AndyIbanez** [jikan-me/jikan#217]
I'm doing a simple GET request to this URL:

```https://api.jikan.moe/v3/user/Leonne/animelist/all```

And it's returning:

```
{
    "error": "Failed to parse 'https://myanimelist.net/animelist/Leonne/load.json?offset=0&status=7'"
}
```

This same call was working fine a few hours ago.

(Apologies if asking for help is preferred on the Discord channel - the invitation link on the Jikan website has expired).

**Comment by AndyIbanez** [comment]
Of course it fixes itself the moment I open an issue about it...

**Comment by purplepinapples** [comment]
I've had this happen a few times, not sure what causes it, but waiting for 5/10 seconds and then re-requesting typically fixes it.

Alternatively, you could make the requests to MAL directly, as jikan is just parsing this page: 

https://myanimelist.net/animelist/Leonne/load.json?offset=0&status=7

https://myanimelist.net/animelist/Leonne?status=2 would become

https://myanimelist.net/animelist/Leonne/load.json?offset=0&status=2
https://myanimelist.net/animelist/Leonne/load.json?offset=300&status=2
https://myanimelist.net/animelist/Leonne/load.json?offset=600&status=2
....

The request you did above is for this page: 
https://myanimelist.net/animelist/Leonne?status=7

So the equivalent json requests are:
https://myanimelist.net/animelist/Leonne/load.json?offset=0&status=7
https://myanimelist.net/animelist/Leonne/load.json?offset=300&status=7
https://myanimelist.net/animelist/Leonne/load.json?offset=600&status=7
https://myanimelist.net/animelist/Leonne/load.json?offset=900&status=7
...

You could make a request to https://api.jikan.moe/v3/user/Leonne
to get the number of watching/completed/on-hold/dropped/ptw entries and therefore how many times you have to add 300 to the `offset` parameter to request a users entire list.

**Comment by AndyIbanez** [comment]
Thanks.

The Discord link I clicked on jikan.moe was expired. I'm not sure if it's the same one but the one you gave me works fine now.

**Comment by irfan-dahir** [comment]
Hi, as per our discussion over on Discord; the error is due to heavy rate limiting being imposed on one of Jikan's servers from MyAnimeList. This is due to high load on the servers. The REST API is not catching the proper exception for this request on 429, so it's going with the generic "Failed to parse" message.

Since anime/manga list caching is just for 5 minutes, the occurrence is more noticeable than other types of requests which are cached for 6~ hours.

I've **temporarily** implemented a stricter rate-limiting from Jikan on requests to prevent any sort of abuse. This will not affect nominal API calls that apps usually make.

**Comment by irfan-dahir** [comment]
Jikan will now appropriately respond when it fails to get the user list from MAL due to rate limiting.
