### ISSUE TITLE
[Feature Request] Get affinity with friends

### ISSUE THREAD

**Issue by sam5558** [jikan-me/jikan#218]
Hello,
First of all, thanks for this interesting project.
I'm wondering if there's (by any chance) a way to get affinity with friends ? If we can use this syntax and get a metric with affinity percentage of each friend that would be great i think. Maybe this issue can be flagged with `improvement` flag if it's not available right now.
Target code (eg. JikanPy):
`# friends info`
`myfriends = jikan.user(username='Guts__', request='friends')`

But anyway great project.

**Comment by purplepinapples** [comment]
Wouldn't be trivial as Jikan doesn't log you in, its just scraping the public page.

However, since MAL Is just performing [Pearson's Correlation Coefficient](https://github.com/erkghlerngm44/aniffinity/blob/master/aniffinity/calcs.py#L13), you can download both lists and calculate affinity yourself ([In case you're curious on how MAL affinity works](https://purplepinapples.github.io/mal-affinity/)).

Theres a python package called [`aniffinity`](https://github.com/erkghlerngm44/aniffinity) that does this for you.

For some reason it doesn't implement any rate limiting, so working off the `load.json` endpoint doesn't work for larger lists; I created a fork on my Github that implements rate limiting; so you can install like:

`python3 -m pip install git+https://github.com/purplepinapples/aniffinity`

Example execution:

```
>>> from aniffinity import Aniffinity
>>> af = Aniffinity("Guts__", base_service="MyAnimeList")
>>> af.calculate_affinity("Xinil", service="MyAnimeList")
Affinity(value=19.64363617549836, shared=74)
```

**Comment by sam5558** [comment]
Thank you so much @purplepinapples,
Tbh i've found yesterday a pretty similar python script to [yours](https://github.com/erkghlerngm44/malaffinity) but sadly didn't work.
I can play a bit with your script and a wrapper to automatically fetch my friends list, get all affinity scores, rank them by desc values and display them as an output. (can be interesting and funny) :)

**Comment by janvernieuwe** [comment]
If you think you can get login working, we and are willing to make a PR for this, we can perhaps add this functionality to the parser.

**Comment by purplepinapples** [comment]
@sam5558 Because of erkghlerngm44/aniffinity#9 you can now:

`python3 -m pip install git+https://github.com/erkghlerngm44/aniffinity`

and use the `wait_time` argument to wait between paginated requests:

```python
>>> from aniffinity import Aniffinity
>>> af = Aniffinity("Guts__", base_service="MyAnimeList", wait_time=2)
>>> af.calculate_affinity("Xinil", service="MyAnimeList", wait_time=2)
Affinity(value=19.64363617549836, shared=74)
```

It defaults to 2 seconds, I'm just including for clarity.

**Comment by sam5558** [comment]
Thank you for the info. I never got a `RateLimitExceededError` tbh.
I'm still working on a script to fully automate all usernames, affinities & shared anime.
I've also noticed that the Pearson's correlation coefficient doesn't give the exact percentage (sometimes i get 2 or 3% of difference between what myanimelist states and what the script outputs)

**Comment by irfan-dahir** [comment]
I hope the solutions above worked for you. 

Currently there's no plans to add this sort of feature as it's something that could be done on the client-side and Jikan doesn't support POST requests (#219) in order to be able to scrape that sort of information by logging the user in and checking against another.

I will be closing this issue, please feel free to open another one if you've any other queries.
