### ISSUE TITLE
[Anime|Manga] Just Added

### ISSUE THREAD

**Issue by irfan-dahir** [jikan-me/jikan#222]
- https://myanimelist.net/anime.php?o=9&c%5B0%5D=a&c%5B1%5D=d&cv=2&w=1
- https://myanimelist.net/manga.php?o=9&c%5B0%5D=a&c%5B1%5D=d&cv=2&w=1

Anime/Manga that have just been added to the MyAnimeList database. 

Not sure how this would be requested on the Jikan REST API.

Edit: Maybe `/justadded/{manga|manga}` :thinking:

**Comment by GSculerlor** [comment]
`justaddded/{anime|manga}` is not bad

**Comment by purplepinapples** [comment]
Since the [just added page](https://myanimelist.net/anime.php?o=9&c%5B0%5D=a&c%5B1%5D=d&cv=2&w=1) is just a search query with the top having the highest MAL ID, and you're already planning to add [order by](https://github.com/jikan-me/jikan/issues/220) to searches, why not have this be on the search endpoint with `orderby=id`?

I found some interesting stuff trying to figure out what reverse `justadded` would be:

https://myanimelist.net/anime.php?o=0: Alphabetical Title
https://myanimelist.net/anime.php?o=1: Reverse Alphabetical Title
https://myanimelist.net/anime.php?o=2: ??? might be score in increasing order, but seems strange. This may be because MAL doesnt officially score items till they pass some threshold of members/start airing
https://myanimelist.net/anime.php?o=3: score in decreasing order (highest first)
https://myanimelist.net/anime.php?o=4: highest ep count first
https://myanimelist.net/anime.php?o=5: lowest ep count first
https://myanimelist.net/anime.php?o=6: lowest "type" first
https://myanimelist.net/anime.php?o=6&w=2: highest "type" first

No clue what the `w=2` param is, but these searches are equivalent:

https://myanimelist.net/anime.php?o=6
https://myanimelist.net/anime.php?o=6&w=1
so for some of these `w=1` is low->high and `w=2` must be high->low.

https://myanimelist.net/anime.php?o=7: Most Popular
https://myanimelist.net/anime.php?o=7&w=2: Least Popular
https://myanimelist.net/anime.php?o=8 or https://myanimelist.net/anime.php?o=8&w=1: Highest Rating (G, PG, Rx) first; i.e. Rx first.
https://myanimelist.net/anime.php?o=8&w=2: Lowest Rating first, i.e. Unknown -> G -> PG -> PG-13 -> R -> R+, Rx
https://myanimelist.net/anime.php?o=9: Highest MAL ID first
https://myanimelist.net/anime.php?o=9&w=2: Lowest MAL ID first

**Comment by irfan-dahir** [comment]
Woahh, thank you so much. This saves me a great deal of time!

`orderby=id` would definitely work instead of `/justadded`. 
You're right on regarding the `w` property.

https://myanimelist.net/anime.php?o=9&w=1 : Just Added
https://myanimelist.net/anime.php?o=9&w=2 : Starts from the first entry ever

**Comment by irfan-dahir** [comment]
Closing as the implementation would be with #220 instead.

Thank you for your feedback guys!
