### ISSUE TITLE
[Request] Anime Episode Details

### ISSUE THREAD

**Issue by ZeeRooo** [jikan-me/jikan#229]
Hi, i have just noticed that MAL provides sinopsis in each episode and Jikan does not.
Take a look: 
https://api.jikan.moe/v3/anime/185/episodes

https://myanimelist.net/anime/185/Initial_D_First_Stage/episode/1

As we said in Discord, implement something like /anime/episode/1 would be great.
Congrats for the API.

**Comment by jaredallard** [comment]
I think it'd be better if this could be included in the list of episodes, otherwise you'd have to hit the endpoint `O(n)` times which is bad for both the server and client. Also, would be amazing if this was added soon! :tada:

**Comment by seanbreckenridge** [comment]
Unless I'm missing something, I don't think we can 'choose' to include it with the list of episodes, the data isn't available on that page.

https://myanimelist.net/anime/185/Initial_D_First_Stage/episode

doesn't include the information, each `tr` is:

```
<tr class="episode-list-data">
        <td class="episode-number nowrap">1</td>
        <td class="episode-video nowrap"></td>
        <td class="episode-title"><a href="https://myanimelist.net/anime/185/Initial_D_First_Stage/episode/1" class="fl-l fw-b watched">The Ultimate Tofu Store Drift</a>
          <br><span class="di-ib">Kyuukyoku no Toufu ya Drift&nbsp;(究極のとうふ屋ドリフト)</span>
        </td>
        <td class="episode-aired nowrap">Apr 19, 1998</td>
        <td class="episode-forum ac nowrap">
          <a href="https://myanimelist.net/forum/?topicid=162206"><i class="fa fa-comments mr4"></i>Forum</a></td>
      </tr>
```

which only includes the link to the episode page (https://myanimelist.net/anime/185/Initial_D_First_Stage/episode/1), which includes the information.

**Comment by jaredallard** [comment]
@seanbreckenridge Yeah, I realized that, sucks for my use cases but oh well.

**Comment by irfan-dahir** [comment]
Added the following data:

| Property | Type | Remarks |
| ------------- | ------------- | ------------- | 
| Episode ID | Integer | - |
| URL  | String | - |
| Title | String | - |
| Title Japanese | String | - |
| Title Romaji | String | - |
| Duration | Int | Converts `00:24:00` (e.g) into seconds |
| Aired | DateTimeImmutable/ISO8601 | - |
| Filler | Bool | - |
| Recap | Bool | - |
| Synopsis | String | - |

Haven't added characters/staff since it's already in the anime characters/staff endpoint. There's Crunchyroll information too, but it's a bit complicated and not all anime support it so would need to look further into that.
Meanwhile I'm open to anything else we can parse from the page that might be useful.


Will transfer the issue to the REST API repo once we're ready to begin v4 development.

**Comment by ZeeRooo** [comment]
It's a bit too late but i'm seeing some progress here so, am i missing something or there's no synopsis? 

> {
      "episode_id": 1,
      "title": "Asteroid Blues",
      "title_japanese": "アステロイド・ブルース",
      "title_romanji": "Asteroid Blues ",
      "aired": "1998-10-24T00:00:00+00:00",
      "filler": false,
      "recap": false,
      "video_url": "https://myanimelist.net/anime/1/Cowboy_Bebop/episode/1",
      "forum_url": "https://myanimelist.net/forum/?topicid=29264"
    },
```

**Comment by irfan-dahir** [comment]
Hey @ZeeRooo , sorry for the late response. The feature has been added to the parser but not to the REST API yet.

It will be added in for the next major release (v4) of the REST API (it will require a new endpoint) as soon as we're done with the [roadmap here](https://github.com/jikan-me/jikan/projects/4).

Will keep you updated here and in the discord
