### ISSUE TITLE
Spring 2020 endpoint returning current season data

### ISSUE THREAD

**Issue by AniLeo** [jikan-me/jikan#238]
https://api.jikan.moe/v3/season/2020/spring

Should be returning data from
https://myanimelist.net/anime/season/2020/spring

But it's returning current season data (Fall 2019)

**Comment by irfan-dahir** [comment]
This is due to cache. When a seasonal page does not exist, it redirects to the current season - i.e currently Fall 2019.
Spring 2020 is a relatively new page. At the time of scraping it probably did not exist when someone made that request.
Give it 1-2 days for the old cache to expire, it should then return the correct response.

**Comment by AniLeo** [comment]
Data recached, now returns the proper information. Closing as solved.
