### ISSUE TITLE
last_page on search/* endpoint displaying incorrect values.

### ISSUE THREAD

**Issue by MaddyUnderStars** [jikan-me/jikan#261]
Reported on Discord but was drowned out: https://discordapp.com/channels/460491088004907029/488736492454412298/669570916866457613

In the request https://api.jikan.moe/v3/search/anime?q=Fate%20Zero the `last_page` argument is 20.
[Viewing page 20](https://api.jikan.moe/v3/search/anime?q=Fate%20Zero&page=20) gives us a `last_page` of 36.
[Viewing page 36 ](https://api.jikan.moe/v3/search/anime?q=Fate%20Zero&page=36) gives us a `last_page` of 35.

This occurs on all search endpoints, and I believe is because the [page select](https://myanimelist.net/anime.php?q=Fate+Zero) on MAL only displays up to page 20 before displaying the real last page ( or 20 more? ) when near.
The `last_page` of 35 thing is probably because the parser fetches all links, however the current page is not a link.

**Comment by irfan-dahir** [comment]
Hey, thanks for highlighting this here.

It's as you said
> This occurs on all search endpoints, and I believe is because the page select on MAL only displays up to page 20 before displaying the real last page ( or 20 more? ) when near.

This is definitely a logic issue rather than a parser issue. Jikan assumes the last link is the last page but it seems MAL shows more pages once that "last page" is clicked on.

The appropriate fix for this perhaps would be a boolean `has_next_page` instead of an unreliable integer.

Though, I think this would be rather a major change/fix for now but something for Jikan v4 since we'd be replacing `last_page`.

I'll keep this issue open until we've done that. 👍

**Comment by irfan-dahir** [comment]
**TODO**
- [ ] refactor `last_page` to `last_visible_page` (integer)
- [ ] add `has_next_page` (boolean)

**Progress**
- [ ] Anime Search
- [ ] Manga Search
- [ ] People Search
- [ ] Character Search
- [ ] Users Search

Does not apply to Club Search as there is no `last_visible_page` - only a "More" button. Will have to return `last_visible_page` as either
1. The current page 
2. As `null`

There are more pages like this.

**Comment by irfan-dahir** [comment]
Closing because the above fix has been implemented in [v4](https://api.jikan.moe/v4/anime?q=Fate/zero).
