### ISSUE TITLE
Support For Endpoints Requiring Authentication?

### ISSUE THREAD

**Issue by DevonJSmith** [jikan-me/jikan#278]
Hello, 

I was looking through the Jikan API documentation and it seems to be focused on GET requests (correct me if I'm wrong).

I have seen example of documentation for MAL's authenticated endpoints (see: https://github.com/SuperMarcus/myanimelist-api-specification), which would allow requests to update a User's library.

Is this kind of functionality planned for Jikan, or is it a different direction than what is intended (since this would require user authentication)?

**Comment by irfan-dahir** [comment]
Hi,

Unfortunately, this feature is not planned for the API. It's not possible to implement Auth (POST) based requests server-side due to imminent blocking from MAL. 

There is a PoC here: https://github.com/jikan-me/jikan-auth
The [readme](https://github.com/jikan-me/jikan-auth/blob/master/README.md) details on why it's not viable for the API.

I've also written out a specification for using their website's API to update user lists. All the apps these days are using this approach for MAL. This is what the PoC is based on however, it's more of a client-side solution rather than server side.
https://github.com/jikan-me/jikan-auth/blob/master/SPECIFICATION.md

**Comment by DevonJSmith** [comment]
Ah I see, I wasn't aware of the `jikan-auth` repo, so thank you for sharing that with me.

I figured something like this wasn't possible, but I'm thankful for the explanation as to why. Thanks!
