### ISSUE TITLE
Is it possible to build a  Users, Anime info, Rating, and more as the Anime Recommendations Database on Kaggle

### ISSUE THREAD

**Issue by JonathanSum** [jikan-me/jikan#309]
Hi, I have been looking for a way to build an updated version dataset like the one in Kaggle's Anime Recommendations Database.
https://www.kaggle.com/CooperUnion/anime-recommendations-database?select=rating.csv
The one at Kaggle is about 2018 using the old official API.
Thus, I want to find an API that can recreate a 2018 to 2020 dataset.  I read the doc, but it does not have this function. Does anyone know how to do it?

**Comment by irfan-dahir** [comment]
Anime recommendations are currently not supported.
We're working on a newer version of the API that'll introduce a Recommendations endpoint.

However, no solid ETA on the new version at the moment though due to this issue:
https://github.com/jikan-me/jikan-rest/issues/123#issuecomment-663598909

**Comment by JonathanSum** [comment]
@irfan-dahir 
**I am not asking for the Recommendations.**
I am asking how to extract user-id, rating, and maybe other information about the anime, so **I can build Recommendations and a PCA map.**
Just like this one:


So, I am saying how to extract data so I can build it on my own!

**What I want to build is a Deep Learning model that learns from the users and build a bais map!**

See this one? This is what I build with the data from 2017 with only users id and rating

![inbox_3118828_4c859e3ecf37d9c8685a8c5426371f7c_Anime Map icon](https://user-images.githubusercontent.com/21982975/88714199-615fb700-d0a7-11ea-8fb3-9169bf421cc0.png)

**Comment by irfan-dahir** [comment]
Ah.

So by "rating" you mean user score on an anime. You'll have to fetch every user's anime list. Entries on that list would have what they scored on it. This can be accessed in a few ways.

1. You can usually do it through Jikan API. But you'll have to set up your [own instance](https://github.com/jikan-me/jikan-rest#getting-started) because it's [not working on our end](https://github.com/jikan-me/jikan-rest/issues/123#issuecomment-663598909)
2. You can fetch user lists directly from MAL through their web API.
https://myanimelist.net/animelist/nekomata1037/load.json
It only returns 300 entries at once so you'll have to use `offset` to paginate
https://myanimelist.net/animelist/nekomata1037/load.json?offset=300
3. Use MAL's official API. You'll need to access it via OAuth2.0. MAL API can be accessed through [Profile Page > Edit Profile > API (tab)](https://myanimelist.net/apiconfig). Then use their API to fetch user lists.

> Rating.csv
> 
> user_id - non identifiable randomly generated user id.
> anime_id - the anime that this user has rated.
> rating - rating out of 10 this user has assigned (-1 if the user watched it but didn't assign a rating).

You currently can't access a user through their user id. **You need to know their username.** I think you'd have to scrap those from [user search](https://myanimelist.net/users.php) as Jikan currently does not support it.

Hope that helps.
