### ISSUE TITLE
[OFFICIAL] Generated Issue: ParserException

### ISSUE THREAD

**Issue by AniLeo** [jikan-me/jikan#328]
Please fill out the details below.

**Summary:** Got this error when requesting 2021 Summer, the same happens with 2021 Fall

**Steps to reproduce:** Request https://api.jikan.moe/v3/season/2021/summer or https://api.jikan.moe/v3/season/2021/fall

 ### Additional Details 
 **Jikan Parser Version**: ```v2.16.14@b931a4fe6fc0b7b1769bdf84f89ef2b79b5d4f42```
**PHP:** ```7.3.20-1+ubuntu18.04.1+deb.sury.org+1```
**Redis**: ```Connected```
**Exception:** ```Jikan\Exception\ParserException```
**Code:** ```0```
**Message:** ```Failed to parse 'https://myanimelist.net/anime/season/2021/summer'```
**Trace:** ```/var/www/jikan/vendor/jikan-me/jikan/src/Exception/ParserException.php on line 24```
**Request:** `GET /v3/season/2021/summer`

**Comment by irfan-dahir** [comment]
Thanks for the report.

It seems Summer 2021 and Fall 2021 pages do not exist at the moment on MAL so it redirects the page to https://myanimelist.net/anime/season instead.

So the parser fails here; pages that exist have been tested and work fine.

Looking into adding an appropriate response for something like this.

**Comment by irfan-dahir** [comment]
I was wondering why MAL was even returning those seasons on the archive page if the pages didn't exist. Turns out it wasn't. There was a really old bug that returned all seasons regardless of whether they exist on the page or not.

MAL:
![image](https://user-images.githubusercontent.com/9166451/95985495-194a6800-0e3e-11eb-8cd2-65e58c790fc5.png)
Jikan:
![image](https://user-images.githubusercontent.com/9166451/95985540-26675700-0e3e-11eb-9c4b-a8d1e69c71cb.png)

So that got fixed too, haha.

Anyways, for the issue at hand. It's resolved, pages that don't exist return this now:
![image](https://user-images.githubusercontent.com/9166451/95985675-4bf46080-0e3e-11eb-9446-e64edfe124d6.png)


[v2.16.15](https://github.com/jikan-me/jikan/releases/tag/v2.16.15)
