### ISSUE TITLE
[Request] Auto-generated recommendations

### ISSUE THREAD

**Issue by jamesqo** [jikan-me/jikan#338]
![autorec](https://user-images.githubusercontent.com/9159214/106399265-9990db00-63e5-11eb-85e4-f23ced8cdaff.PNG)

It would be helpful to expose these in the API, currently I don't see a way to get these except by scraping MAL manually.

**Comment by irfan-dahir** [comment]
These recommendations are based on the logged-in user, we can't get those since we don't support authenticated requests.

However, anime/manga community recommendations are in the works - we get those by parsing https://myanimelist.net/recommendations.php?s=recentrecs&t=anime

You can test it out here: https://api.jikan.moe/v4-alpha/recommendations/anime
