### ISSUE TITLE
User anime list entry title serialization edge case

### ISSUE THREAD

**Issue by irfan-dahir** [jikan-me/jikan#343]
```
I have noticed the anime titled "86" is serialized into JSON without the quotes (so it becomes an integer). This is breaking, for example, the Jikan .NET API package, since it is expecting a string which in JSON requires quotes. Is this something that needs fixing on the Jikan server side?

This behaviour also seems to differ between different requests, for example in the anime request it seems ok, but in the user animelist request it is not.
Test request: https://api.jikan.moe/v3/user/test86anime/animelist/all
```

Ref: https://discord.com/channels/460491088004907029/462991054619148288/825393730805956660

Additional notes:

The same thing could apply to manga titles from the manga list.

**Comment by N0D4N** [comment]
The same bug exists with user's tags inside list entries, if user have written only number inside tags, it is being serialized as number instead of string, as tags should be serialized into.
So i think MAL serializes everything, that can be converted to number, as number, being it integer or floating point numbers, even if logically there should be string.
Test requests (look for mangas with ids `115070`, `120974`):
* MAL https://myanimelist.net/mangalist/N0D4N/load.json
* Jikan v3 https://api.jikan.moe/v3/user/N0D4N/mangalist/all
* Jikan v4-alpha https://api.jikan.moe/v4-alpha/users/N0D4N/mangalist/all

Also if user have written `0` inside tags Jikan v3 and v4-alpha serializes it to `null` instead of converting it to `"0"` or passing it directly as `0`
Test requests (look for manga with id `132912`): 
* MAL https://myanimelist.net/mangalist/N0D4N/load.json?s=DRCL&publishing_status=1
* Jikan v3 https://api.jikan.moe/v3/user/N0D4N/mangalist/all?q=DRCL&publishing_status=publishing
* Jikan v4-alpha https://api.jikan.moe/v4-alpha/users/N0D4N/mangalist/all?q=DRCL&publishing_status=publishing      

Interesting Note  
Also MAL removes all `0` digits before any other digit in digit only anime/manga title or digit only tags
* Sample for title, look for anime with id `29978`. On MAL page its title is `001` however in `load.json` its being displayed simply as `anime_title: 1` https://myanimelist.net/animelist/N0D4N/load.json?s=001 . In animelist its being displayed as `1` too https://myanimelist.net/animelist/N0D4N?s=001
* Sample for tags, look for manga with id `115727` its being returned as `123`, however i've written it as `000123` inside tags field, unfortunately i dont think i can prove it without video recording, but you can try to do the same and see results https://myanimelist.net/mangalist/N0D4N/load.json?s=Batuque

**Comment by irfan-dahir** [comment]
The default value for tags seems to be `0` - which should be null. So we can use that as a way to detect whether it has any tags or not, and respectively keep returning null for BC as well.

Meanwhile, we can go ahead and typecast `title` and `tags` as a string.


> Sample for title, look for anime with id 29978. On MAL page its title is 001 however in load.json its being displayed simply as anime_title: 1 https://myanimelist.net/animelist/N0D4N/load.json?s=001 . In animelist its being displayed as 1 too https://myanimelist.net/animelist/N0D4N?s=001
Sample for tags, look for manga with id 115727 its being returned as 123, however i've written it as 000123 inside tags field, unfortunately i dont think i can prove it without video recording, but you can try to do the same and see results https://myanimelist.net/mangalist/N0D4N/load.json?s=Batuque


Interesting find indeed. Unfortunately, the data passed (extra 0s) seems lost so I'm not sure we can get that back.

**Comment by N0D4N** [comment]
> The default value for tags seems to be `0` - which should be null

Default value for tags is empty string - `""`. So Jikan should return null in case of `""` and not `0`
You can see it with this request https://myanimelist.net/animelist/N0D4N/load.json , just filter json by `tags` and expand all list entries. It looks like this for me
![image](https://user-images.githubusercontent.com/50947930/114297001-e7e1ea80-9ab6-11eb-9417-f69aa6a48ef0.png)

> Meanwhile, we can go ahead and typecast title and tags as a string.

Great!

> Interesting find indeed. Unfortunately, the data passed (extra 0s) seems lost so I'm not sure we can get that back.

In case of title it seems possible to retrieve original title from `anime_url: "/anime/29978/001"`. But i think it would extra complicate Jikan logic with low benefits, and since MAL displays it as `1` in list, even if it's wrong, Jikan should display it like that too.

**Comment by irfan-dahir** [comment]
> Default value for tags is empty string - "". So Jikan should return null in case of "" and not 0
You can see it with this request https://myanimelist.net/animelist/N0D4N/load.json , just filter json by tags and expand all list

You're right. I've pushed a commit to patch this.

`0` will now be returned as `"0"` instead of `null`.

**Comment by irfan-dahir** [comment]
![image](https://user-images.githubusercontent.com/9166451/114297757-00103480-9acc-11eb-9c8e-11a92ffa1a99.png)

Patched the public API. Any existing cache with the old values should take up to an hour to get replaced.
