### ISSUE TITLE
[OFFICIAL] Generated Issue: ParserException

### ISSUE THREAD

**Issue by axelbrians** [jikan-me/jikan#386]
**Summary:**
Get error response when hitting `https://api.jikan.moe/v3/schedule/monday`. The response told me to post generated issue here. So here I am.

**Steps to reproduce:**
Run the Request Schedule Example from the links below.
https://jikan.docs.apiary.io/#reference/0/schedule/schedule-request-example+schema?console=1

 ### Additional Details 
 **Jikan Parser Version**: ```v2.18.13@d41c4535bb739824c61ae22192c41eb3b705399c```
**PHP:** ```7.4.23```
**Redis**: ```Connected```
**Exception:** ```Jikan\Exception\ParserException```
**Code:** ```0```
**Message:** ```Failed to parse 'https://myanimelist.net/anime/season/schedule'```
**Trace:** ```/var/www/jikan/vendor/jikan-me/jikan/src/Exception/ParserException.php on line 24```
**Request:** `GET /v3/schedule/monday`

**Comment by irfan-dahir** [comment]
**For v3 users**

MAL has changed the way this card looks like. This issue affects endpoints like search, genre search, schedule, etc.
![image](https://user-images.githubusercontent.com/9166451/148605353-4e27315f-e97b-4e79-9c44-83bcc2db373e.png)

1. `members` now shortens the value if it's in the thousands.

e.g `241,522` is now `241K` and so the actual member count is _not_ viewable and only estimated at this point. e.g Jikan will return `241,000` instead.
Same applicable with member count in millions.

2. `licensors` are not longer returned. So v3 now just returns it as an empty array.

3. `type` is no longer returned in seasonal whereas it's returned in anime listing by genre. So v3 now just returns it as `null` because of HTML inconsistencies. 

4. `airing_date` is no longer returned in anime listing by genre where as it's returned in seasonal. This works on seasonal but will return `null` on genres.

---
:information_source: 

**Main Anime/Manga endpoints are not affects as the data is appropriately returned.**

**And neither is v4 affected as it queries entries internally on such endpoints.** If you need this information, please upgrade to v4.
