### ISSUE TITLE
Add scheduled github action for tests

### ISSUE THREAD

**Issue by pushrbx** [jikan-me/jikan#441]
We'd like to get updated if the tests break over time, so we will know if the DOM of MAL pages have changed.

**Comment by nerg4l** [comment]
This one is a bit problematic if we don't use cache. For example forum and user friend list changes constantly.

**Comment by irfan-dahir** [comment]
@nerg4l I was thinking the same thing. Not sure what an approach for this would be if we were to update the cache periodically.

**Comment by nerg4l** [comment]
Then the tests will fail after a week. Not sure how we can make sure to have consistent data with up to date HTML structure. We could maybe run tests against less popular (almost dead) anime, manga, forum, etc.

**Comment by pushrbx** [comment]
How about some DIY low budget rotating proxy?
- https://github.com/kitabisa/mubeng
- VPS with multiple public ips (3 or 4)
- A subnet on the VPS which has one IP per container running a squid proxy
- Each container of squid proxy would be bound to one public IP

The configuration is a bit complicated, afaik you need to set routes in iptables.

**Comment by irfan-dahir** [comment]
To add to the discussion: An outdated cache for some tests might benefit.

For example, I just added `approved` to the Anime/Manga model to help detect entries that have been deleted from MAL or are not approved. So we can remove them from the search on the REST API or delete them in a scheduled sweep.
Commit: https://github.com/jikan-me/jikan/commit/be4bc5759dc960ca1ec232092fba14ceb4fb46ba

This adds a fixture of entries which are unapproved: https://github.com/jikan-me/jikan-fixtures/commit/197b8b4c5444faa083c4b9a1ea0123eb52b887d9
As of testing: https://myanimelist.net/anime/48104 is pending approval

Since this would later be either
1. Approved by MAL ([XPath](https://github.com/jikan-me/jikan/blob/be4bc5759dc960ca1ec232092fba14ceb4fb46ba/src/Parser/Anime/AnimeParser.php#L102) will no longer be valid)
2. Rejected by MAL (deleted entry, MAL will return 404 instead)

It would benefit having their fixtures remain unchanged to test against approval status.
