### ISSUE TITLE
getAnimeFullById does not include statistics

### ISSUE THREAD

**Issue by JoshuaWalsh** [jikan-me/jikan#470]
The documentation for this method says "Returns complete anime resource data", but the response does not include statistics.

It would be fantastic if this method could include statistics, as it would halve the amount of requests I have to make to Jikan..

**Comment by irfan-dahir** [comment]
By "complete anime data", I'm referring to what was provided in v3 - as v4 breaks the data down to keep the schema uniform throughout.

[Entry Statistics](https://myanimelist.net/anime/1/Cowboy_Bebop/stats) is a separate page that is parsed separately and cached rather than indexed at the moment. So due to those technical limitations, it's impossible to include it and any sub-pages of an anime within a single response.
