### ISSUE TITLE
Some pages return a bool "false"

### ISSUE THREAD

**Issue by zenrac** [jikan-me/jikan#55]
A lot of person page return false, 
e.g  
jikan.me/api/v1.1/person/2 or jikan.me/api/person/2
jikan.me/api/person/3
jikan.me/api/person/4
even if the person is supposed to exist (e.g Rie Kugimiya id = 8 but http://jikan.me/api/person/8 return false)

**Comment by irfan-dahir** [comment]
Hey @zenrac, sorry for the late response. I'm looking into what could've been causing it.

Meanwhile, I've reset the cache for persons endpoint and it should work now! Do let me know here if this reoccurs for you.

**Comment by zenrac** [comment]
Now it works! That is weird

**Comment by BlackSynder** [comment]
I'm seeing this again, specifically with `http://jikan.me/api/v1.2/person/869` although I'm getting reports of more that dont work. @irfan-dahir have any idea whats causing it?

**Comment by irfan-dahir** [comment]
It seems like we were out of disk space + we've been getting massive amount of requests and MAL is blocking the connection on too many requests. Hence the "false" returns.

I'm looking for solutions.

**Comment by Vergo777** [comment]
Hey irfan, thanks a lot for this API, such a pleasure to grab data from this rather than MAL's opaque and clunky XML endpoints. 

Just want to let you know that I'm facing the same issue atm, but again, only with specific IDs as mentioned above. Eg. https://jikan.me/api/v1.1/person/2 always throws up false for me while the rest seem to work fine. Perhaps a caching issue again?

**Comment by BlackSynder** [comment]
@Vergo777 it seems that using the `v1.2` endpoint solves this for now, not sure how intentional it is.

**Comment by Vergo777** [comment]
@BlackSynder cheers for the suggestion! It almost worked, but unfortunately 1.2 throws up an error with this one http://jikan.me/api/v1.2/person/67 :(

**Comment by BlackSynder** [comment]
I see. Hope it gets solved soon.

**Comment by irfan-dahir** [comment]
Hi, sorry about this. It's now mostly due to Jikan getting rate limited by MAL, hence the "false". 

If too many requests are made from Jikan to MAL, the REST service ends up getting rate limited for a little while and *any* requests within that duration to MAL return a "false" response.
There's a very low chance that this occurs since most of the data is cached but then again, there's not much we can do about it either when it does occur.

The upcoming REST version will replace this with an error and not cache the response "false" as-is. Meanwhile, I've gone ahead and removed all buggy cache responses so you should be getting valid responses!

-> https://jikan.me/api/v1.1/person/2
-> http://jikan.me/api/v1.2/person/67

If you're planning to make bulk requests to the person/character endpoint, please add a delay in between each request to prevent rate-limiting. 

You don't have to do this for the anime or manga endpoint since they're the most requested endpoints and are mostly cached - whereas there's not as much requests made for the person/character endpoints.

**Comment by BlackSynder** [comment]
Understandable, thanks! I personally don't make that many requests but I'll keep it in mind.

**Comment by irfan-dahir** [comment]
This has been fixed since the new 2.X release!
