### ISSUE TITLE
[REQUEST] Batch API calls

### ISSUE THREAD

**Issue by jakemoritz** [jikan-me/jikan#76]
I'd be really interested in support for batch API calls. An example of this would be a call to get a couple different anime objects by MyAnimeList ID: `https://jikan.me/api/anime/21/22/23/24/...`. This would be useful for applications that want to download a bunch of anime data and then persist it locally. This is a more ideal solution than making a bunch of separate API calls. AnimeNewsNetwork implements batching here: https://www.animenewsnetwork.com/encyclopedia/api.php. Would something like this be possible?

**Comment by irfan-dahir** [comment]
That is a useful feature and it's definitely possible but isn't implemented due to performance related issues. One of them being; Jikan a web scraper for MyAnimeList, which doesn't have direct access to their database to be able to do what ANN achieves. The requests are not stored in a database on Jikan's side either (as per MAL's TOS) - it's temporarily cached for 3 days.

Making batch calls would mean making as many requests there's in the batch, which will most likely get Jikan rate-limited temporarily by MyAnimeList - becoming an inconvenience to other users making use of the API.

Applications shouldn't have an issue with the current method as they can asynchronously request the data from Jikan, rather having to fetch one huge request in order to display them all.

**Comment by jakemoritz** [comment]
Gotcha, I wasn't 100% how Jikan worked. I realize this isn't really possible with MAL's rate-limiting. Thanks for the quick response!
