### ISSUE TITLE
array_walk() expects parameter 1 to be array, boolean given

### ISSUE THREAD

**Issue by xNinjaKittyx** [jikan-me/jikan#90]
So my script does the following:

Grab an anime using the endpoint
`https://api.jikan.me/anime/{anime_id}/episodes/1`

If that gives me a 404 that gives some other error than "File does not exist", I try this endpoint
`https://api.jikan.me/anime/{anime_id}`

If that gives me 404, I print out the error message.

I see this `array_walk() expects parameter 1 to be array, boolean given` on several animes where if I grab the corresponding ID on myanimelist, they exist there.

Some Examples: 97, 200, 186, 840, 852, 858, 874, 880, 878, 903, 917, 909, 960

Please note that sometimes missing animes also return "File does not exist" even though it does exist on myanimelist  (But I'm not logging the ones that return that message... could have false negatives there.)

**Comment by irfan-dahir** [comment]
I went through the IDs you mentioned and they're working fine right now. I'm presuming your script isn't using any delay between the requests. This causes Jikan to be Rate Limited by MyAnimeList. 

Resulting in the "File does not exist" error for anime that even exist. Because a `array_walk() expects parameter 1 to be array, boolean given` here means that the file handle for streaming the file contents of the page is returning `false` being since the request is failing.

So during your request time either of this happened.

1. MyAnimeList was down
2. You were being rate limited from MyAnimeList

Most likely the latter. Please use a delay of 1 second between normal requests and 2 second delay between extended requests (episodes, characters+staff, etc).

**Comment by xNinjaKittyx** [comment]
Hmm, I already had a 1 second delay between all requests, but I'll try again with larger delays. I do have a 30 second sleep time if 429 is returned, but since 404 is being returned instead, it doesn't ever reach that part.

**Comment by irfan-dahir** [comment]
Since extended requests are technically 2 requests, a 2 second (max 3 second) delay will be sufficient. 
I've made a new issue regarding the incorrect response format made by Jikan. https://github.com/jikan-me/jikan/issues/91

**Comment by irfan-dahir** [comment]
It might take a little longer for me to address this issue since it resolves playing around with other methods for fetching header responses from MAL and updating the REST API which is different in its' own terms. Please follow #91 for updates on this particular issue.

Other than that, feel free to open another issue in case you face any other problem.

**Comment by irfan-dahir** [comment]
Issue resolved.
